services:
  pingdirectory:
    image: pingidentity/pingdirectory:11.0.0.0-alpine_3.23.2-al17-edge
    container_name: pingdirectory
    environment:
      - PING_IDENTITY_ACCEPT_EULA=YES
      - SERVER_PROFILE_URL=https://github.com/SHAfoin/icy-5a-iam-2026.git
      - SERVER_PROFILE_PATH=conf
      - PING_IDENTITY_DEVOPS_USER
      - PING_IDENTITY_DEVOPS_KEY
      - USER_BASE_DN=o=insa
      - PD_ENGINE_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
      - PDP_ENGINE_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
      - PDS_ENGINE_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
      - PAZ_ENGINE_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
      - PAZP_ENGINE_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
      - PF_ENGINE_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
      - PF_ADMIN_PUBLIC_BASEURL=https://${PINGFEDERATE_PUBLIC_IP}:9999
      - PF_ADMIN_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
      - PA_ENGINE_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
      - PA_ADMIN_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
    ports:
      - "1389:1389"
      - "1443:1443"
      - "1636:1636"
      - "8989:8989"
    volumes:
      - "./license.lic:/opt/staging/pd.profile/server-root/pre-setup/PingDirectory.lic"
      - ./conf/.sec:/run/secrets
    restart: unless-stopped

  pingadmin:
    image: pingidentity/pingdataconsole:11.0.0.0-alpine_3.23.2-al17-edge
    container_name: pingadmin
    ports:
      - "8080:8080"
      - "8443:8443"
