services:
  pingfederate:
    image: pingidentity/pingfederate:13.0.0-alpine_3.23.2-al17-edge
    container_name: pingfederate
    ports:
      - "9999:9999"
      - "9031:9031"
    environment:
      - PING_IDENTITY_ACCEPT_EULA=YES
      - PD_ENGINE_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
      - PDP_ENGINE_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
      - PDS_ENGINE_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
      - PAZ_ENGINE_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
      - PAZP_ENGINE_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
      - PF_ENGINE_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
      - PF_ADMIN_PUBLIC_BASEURL=https://${PINGFEDERATE_PUBLIC_IP}:9999
      - PF_ADMIN_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
      - PA_ENGINE_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
      - PA_ADMIN_PUBLIC_HOSTNAME=${PINGFEDERATE_PUBLIC_IP}
    volumes:
      - "./license_pingfederate.lic:/opt/out/instance/server/default/conf/pingfederate.lic"
